### ISSUE TITLE
اضافه کردن تگ به لاگ‌ها

### ISSUE THREAD

**Issue by MCSH** [softwaretalks/pangul#5]
<dir dir="rtl">

اضافه کردن تگ به لاگ‌ها جهت دسته‌بندی پیام‌ها

Reference commit: 87650fc
Reference issue: #3 

Example:

[system] Finished parsing config
[health] https://google.com: fail

</div>

**Comment by thebrodmann** [comment]
I will close the issue due to lack of any activity for housekeeping purposes. Feel free to re-open it.
