### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by thebrodmann** [softwaretalks/pangul#8]
There is a great hole for the project at the base chore configuration. Lack of any testing taste.
For this point, I think at least **unit testing** is the best choice for the `pangul`.

As a tech suggestion, I think [jest](https://jestjs.io/) is a good option.

I can configure jest for the project if there is any sense for that.

**Comment by MCSH** [comment]
<div dir="rtl">
چرا از mocha استفاده نکنیم؟ برتری jest چی هست؟

**Comment by thebrodmann** [comment]
There are huge articles and comparisons out there that describes more details on these two testing frameworks.

BTW, I explain some of my personal experience:

- Mocha needs more configurations. Jest has almost zero-configuration. (What kind of developer loves chore? 😒)
- Jest has **builtin** support for snapshot and case testing. In Mocha, you can use these features but it's not as easy as in the Jest.
- Jest has **builtin** powerful mocking and assertion tools. In Mocha, you should configure those separately. (Ok, Mocha makes more flexibility, but personally, I don't need any flexibility in this case)
- Jest is backed by Facebook, that leads to its great community.
- Jest has out of the box code coverage
- And as a personal experience, Jest is faster than Mocha (At least 2 years ago)

However, It was a suggestion that came from my experience with AVA, Jest and Mocha.

**Comment by MCSH** [comment]
<div dir="rtl">
دلایل قانع کننده نیست، به ترتیب:

* موکا هیچ کانفیگ اضافه‌ای لازم نداره شما تست‌هاتو توی پوشه test میذاری و تمام.
* به همراه موکا از چای استفاده می‌کنم همیشه که هم bdd هم assertion بتونم تست داشته باشم که به خوانایی کمک می‌کنه
* فیسبوک از jest پشتیبانی می‌کنه و اون رو برای تست UI بهینه می‌کنه نه تست بکند

جدای این موارد، یکجا بودن این ابزارها واقعا مزیت نیست و ایراد هست. شما بخش بزرگی از اپلیکیشنت رو داری وابسته می‌کنی به این ابزار، در صورتی که تو فلسفه یونیکس هر ابزار باید یک کار رو انجام بده، ولی اون کار رو خوب انجام بده.

**Comment by thebrodmann** [comment]
First of all, let's me notice that Jest is not re-invention of the testing tools (e.g. It uses Istanbul code coverage for out of the box code coverage). Jest just config this tools for real-world usage! (In the most projects this configurations is solid)
So useful tools that you should configure yourself to use it in Mocha is pre-configured to use them without any pain. (This doesn't mean you can't change the configuration)

Also, you said Facebook is intended to optimize jest for UI test. It's not true. **If you have any documentation from Jest or Facebook about that let me know**. If you see a huge community of front-end developers that surround jest, this doesn't mean Jest is for UI.

According to the Jest philosophy:

> Jest is a JavaScript testing framework designed to ensure **correctness of any JavaScript codebase**. It allows you to write tests with an approachable, familiar and feature-rich API that gives you results quickly.

Also, about zero-configuration in Mocha. I think it is not anything more than a lie. I don't see any real-world and practical usage of Mocha without any huge configuration and side tools.

About testing style (TDD, BDD, etc.), Jest doesn't restrict you! you can have anything in this field you want. (If you want to use chai, you can but it is not such a good idea in Jest, because you have it!)

Following links is configuration of Mocha, in mochajs/mocha project:

https://github.com/mochajs/mocha/blob/d0cc3b2e43fe99b265edce8960d13b25d0c98be9/package-scripts.js#L65
https://github.com/mochajs/mocha/blob/d0cc3b2e43fe99b265edce8960d13b25d0c98be9/test/assertions.js#L3
https://github.com/mochajs/mocha/blob/d0cc3b2e43fe99b265edce8960d13b25d0c98be9/test/setup.js#L3

Following links is configuration of Jest, in facebok/jest project:

https://github.com/facebook/jest/blob/4ea8462fc014de6b1c8aecfa77052e20f28fa1a5/package.json#L85
https://github.com/facebook/jest/blob/4ea8462fc014de6b1c8aecfa77052e20f28fa1a5/jest.config.js#L5

**Comment by Hameds** [comment]
resolved in #14
