### ISSUE TITLE
استفاده از session store برای ذخیره سازی اطلاعات

### ISSUE THREAD

**Issue by Hameds** [softwaretalks/pangul#9]
https://github.com/expressjs/session#compatible-session-stores
بعداً با دیتابیس می‌تواند جایگزین شود

**Comment by thebrodmann** [comment]
@MCSH Can we use this library as something rather than a session store?
It doesn't look like the express-session library can serve a role extra than a session middleware. Am I correct?

**Comment by psycho-ir** [comment]
Do we need to keep the session state on the backend? 
If we could use sth like JWT, then we don't need to take care of session store and relevant concerns.

**Comment by MCSH** [comment]
No, we don't need to use the session, and we shouldn't if we are going to use rest.

However, the idea here is that "session store" provides a variety of "drop-in" databases that could easily be used. No extra configurations needed. And we could use it to store the result of health checks OR the health check config this way.

**Comment by psycho-ir** [comment]
I see,
My 2 cents
I don’t think  this is the right approach as the data we do have is time series and none of the supported databases  fit well out of the box for it.

I would suggest to use a Time series DB like:
InfluxDB
KairosDB
or prometheus

All have simple to use libraries and reasonable operators to aggregate time series.

**Comment by Hameds** [comment]
We used [http://docs.sequelizejs.com/](http://docs.sequelizejs.com/) instead so this is irrelevant
